version: '3.8'

services:
  pass-ui:
    image: ghcr.io/eclipse-pass/pass-ui-dev
    container_name: pass-ui
    env_file: .demo_env
    build:
      context: ./.docker/ember-dev
    volumes:
      - ../pass-ui/:/passapp
      - ../pass-ui/node_modules:/passapp/node_modules
    tmpfs:
      - /passapp/tmp
    ports:
      - "7020:7020"
      - "7357:7357"

volumes:
  node_modules:
