name: Continuous Integration
on: [pull_request, workflow_dispatch]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint

  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [ 20 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm run test

  acceptance-test:
    name: "Acceptance test"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Grab pass-docker's .env file
        run: |
          wget 'https://raw.githubusercontent.com/eclipse-pass/pass-docker/main/.env'
        shell: bash

      - name: Build local image
        uses: eclipse-pass/main/.github/actions/node-build@main
        with:
          repository_dir: ${GITHUB_WORKSPACE}
          env_path: ${GITHUB_WORKSPACE}/.env

      - name: Run acceptance tests
        uses: eclipse-pass/main/.github/actions/acceptance-test@main
        with:
          pullimages: missing
