name: Update UI Docker image

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  build:
    if:  github.repository == 'eclipse-pass/pass-ui' && (github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      ENV_FILE: https://raw.githubusercontent.com/eclipse-pass/pass-docker/main/.env

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get current project version
        id: project-version
        run: echo "VERSION=`npx -c 'echo $npm_package_version'`" >> $GITHUB_OUTPUT

      - name: Grab pass-docker's .env file
        run: |
          wget $ENV_FILE
        shell: bash

      - name: Build local image
        uses: eclipse-pass/main/.github/actions/node-build@main
        with:
          repository_dir: ${{ github.workspace }}
          env_path: ${{ github.workspace }}/.env

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Push new Docker images'
        run: |
          docker push ghcr.io/eclipse-pass/pass-ui:${{ steps.project-version.outputs.version }}
